### ISSUE TITLE
About depth supervision

### ISSUE THREAD

**Issue by mkjjang3598** [sinoyou/nelf-pro#3]
Hi, thanks for sharing your great work! Have you tried using depth supervision on your work? Or will the quality be better for some challenging scenes by directly applying some depth supervision methods such as MSE, DSNeRF, or some other methods in nerfstudio losses?

**Comment by sinoyou** [comment]
For simplicity and showing the effectiveness of the core idea, we keep loss number as small as possible. We only use photometric reconstruction loss (mse on RGB), distillation loss (proposal networks) and distortion loss (regularization) as same as mipnerf360. 

We didn't experiment monocular depth priors / SfM point depth for improving the quality but it presumably should help.

**Comment by mkjjang3598** [comment]
Thanks!
